name = "iselodyhereyet-sms"
main = "src/index.ts"
compatibility_date = "2026-04-09"

[vars]
GITHUB_OWNER = "zachjustice"
GITHUB_REPO = "iselodyhereyet"
GITHUB_BRANCH = "main"
GITHUB_FILE_PATH = "status.json"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "iselodyhereyet-images"

[[kv_namespaces]]
binding = "PUSH_SUBSCRIPTIONS"
id = "placeholder-create-with-wrangler"
